## quiet concerns about no visiable binding
utils::globalVariables(c("Worm_Length", "Metadata_Experiment", "Metadata_Plate", "Metadata_Well",
                         "Parent_WormObjects", "num_worms", "model_select",
                         "model", "worm_count", "AreaShape_Center_X", "AreaShape_Center_Y",
                         "remove_outliers", "worm_length_um", "well_outlier_flag",
                         "flag_removed", "sd_wormlength_um", "mean_wormlength_um",
                         "drug", "strain", "concentration_um", "FileName_RawBF",
                         "object_type", "Column", "Row", "Well", "n", "value", "file_name",
                         "well_edge_flag_radius", "assay_name", "assay_type", "plate", "bleach",
                         "diluent", "well_censor", "well_censor_reason", "notes", "str_subset",
                         "name", "dir_path", "small", "total_rows", "filtered", "no.parent",
                         "AreaShape_Area", "po_AreaShape_Area", "non-worm", "worm", "classifier_ObjectFlag",
                         "cluster_flag",
                         "objectFlag_n",
                         "group_n",
                         "objectFlag_group_perc",
                         "grand_n",
                         "outlier_ObjectFlag",
                         "group",
                         "mean_strain_length",
                         "slice_index",
                         "well_id",
                         "checkMV_well_id",
                         "arg",
                         "Image_FileName_RawBF",
                         "file_path",
                         "array_x_pos",
                         "array_y_pos",
                         "obj_center_x",
                         "obj_center_y",
                         "obj_class",
                         "obj_color",
                         "obj_shape",
                         "well_label",
                         "text_anno",
                         "animal_length_um",
                         "obj",
                         "well.id",
                         "cv.n",
                         "titer_WellFlag",
                         # checkBalance
                         "lost",
                         "g.total",
                         "n.lost",
                         "n.kept",
                         "perc.lost",
                         "perc.kept",
                         "type",
                         "n.type",
                         "perc.type",
                         "perc",
                         # checkWF
                         "wellFlag_group_perc",
                         "wellFlag_n",
                         # outlierWF
                         "median_wormlength_um",
                         "outlier_WellFlag",
                         # regEff
                         "coef",
                         "term",
                         "Estimate",
                         "Std. Error",
                         "t value",
                         "Pr(>|t|)",
                         "y",
                         # titerWF
                         "flag_id"
                         ))

## quiets concerns of R CMD check re: the .'s that appear in pipelines
if(getRversion() >= "2.15.1")  {utils::globalVariables(c("."))}
